[package]
name = "network-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
libp2p-identity = { version = "0.2.10", features = ["peerid", "rand"] }
multihash = "0.19.3"
rand = "0.9.1"
rayon = "1.10.0"
seahash = "4.1.0"
