[package]
name = "network-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
rand = "0.9.1"
rayon = "1.10.0"
seahash = "4.1.0"

[profile.release]
codegen-units = 1
lto = true
target-cpu = "native"

[profile.dev]
codegen-units = 1
lto = false
debug = true
