schedule_interval_epochs: 1
worker_inactive_timeout_sec: 120     # 2 min
worker_stale_timeout_sec: 900        # 15 min
worker_unreachable_timeout_sec: 300  # 5 min
replication_factor: 2
scheduling_unit_size: 10
mixed_units_ratio: 0.1
mixing_recent_unit_weight: 10.0
worker_storage_bytes: 549755813888   # 512 GiB
s3_endpoint: 'https://7a28e49ec5f4a60c66f216392792ac38.r2.cloudflarestorage.com/'
dataset_buckets:
  - 'ethereum-mainnet'
scheduler_state_bucket: 'network-scheduler-state'
