schedule_interval_sec: 300
replication_factor: 2
scheduling_unit_size: 10
worker_storage_bytes: 549755813888  # 512 GiB
s3_endpoint: 'https://7a28e49ec5f4a60c66f216392792ac38.r2.cloudflarestorage.com/'
buckets:
  - 'ethereum-mainnet'
