[package]
name = "pg-testkit"
version = "0.1.0"
edition = "2024"

[lib]
name = "pg_testkit"

[dependencies]
scheduler-metadata = { path = "../scheduler-metadata", features = ["auto_explain"] }
anyhow = "1.0.98"
dtor = "1.0.5"
sqlx = { workspace = true }
testcontainers = { version = "0.27.2", features = ["watchdog"] }
testcontainers-modules = { version = "0.15", features = ["postgres"] }
tokio = { version = "1.45.0", features = ["rt", "net", "time"] }
