apiVersion: batch/v1
kind: Job
metadata:
  name: last-block-backfill-mainnet-base
  namespace: secure-mainnet-control-plane
spec:
  completions: 227
  parallelism: 20
  completionMode: Indexed
  ttlSecondsAfterFinished: 1800
  backoffLimit: 0
  suspend: false
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: backfill
          image: subsquid/last-block-backfill:0.4.0
          imagePullPolicy: Always
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']

            - name: SHARD_COUNT
              value: "227"

            - name: AWS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: s3_endpoint
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: s3_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: s3_access_key_secret
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: s3_region

            - name: CLICKHOUSE_URL
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: clickhouse_url 
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: clickhouse_database
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: clickhouse_user
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backfill-secrets
                  key: clickhouse_password

          command: ["/bin/sh","-lc"]
          args:
            - |
              set -euo pipefail
              idx="${JOB_COMPLETION_INDEX}"
              echo "Shard index=$idx"

              python last_block_back_fill.py \
              || { echo "Script failed; sleeping for debug"; sleep 900; exit 1; }

