docker run --net=host \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_ENDPOINT_URL=$AWS_ENDPOINT_URL \
    -e AWS_REGION=auto \
    -e AWS_DEFAULT_REGION=auto \
    -e CLICKHOUSE_URL=$CLICKHOUSE_URL \
    -e CLICKHOUSE_USER=$CLICKHOUSE_USER \
    -e CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD \
    -e CLICKHOUSE_DATABASE=$CLICKHOUSE_DATABASE \
    -e JOB_COMPLETION_INDEX=0 \
last-block-backfill

