#!/usr/bin/env bash
#
# Provision a Cloud SQL user + fresh empty database for a reshuffle-sim run and write env.sh
# (gitignored) with what the pod needs. Run once per environment, then use run-pod.sh.
#
# Prompts for the Cloud SQL instance and namespace (or reuses them from a previous env.sh).
# Defaults, overridable via env:
#   PROJECT    (default: bright-meridian-316511)
#   DB_USER    (default: network-scheduler-user)
#   DB_HOST    (default: the instance's private IP, via gcloud)
#   DB_PORT    (default: 5432)
#   DB_SSLMODE (default: require)
#
# Password and DB name are randomised: reshuffle-sim migrates on connect and needs an empty DB.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$DIR/env.sh"

PROJECT_DEFAULT="bright-meridian-316511"
DB_USER_DEFAULT="network-scheduler-user"
DB_PORT="${DB_PORT:-5432}"
DB_SSLMODE="${DB_SSLMODE:-require}"

# Recover a previous env.sh's settings into PREV_* (via subshell, so it can't clobber the current
# environment) to offer reusing the instance + namespace.
PREV_PROJECT=""; PREV_INSTANCE=""; PREV_NAMESPACE=""; PREV_DB_USER=""; PREV_DB_NAME=""
if [ -f "$ENV_FILE" ]; then
    # shellcheck source=/dev/null
    { read -r PREV_PROJECT; read -r PREV_INSTANCE; read -r PREV_NAMESPACE; read -r PREV_DB_USER; read -r PREV_DB_NAME; } < <(
        . "$ENV_FILE"
        printf '%s\n%s\n%s\n%s\n%s\n' "${PROJECT:-}" "${INSTANCE:-}" "${NAMESPACE:-}" "${DB_USER:-}" "${DB_NAME:-}"
    )
fi

# env.sh is rewritten only at the end. If provisioning aborts partway, warn that it's stale, so
# run-pod.sh doesn't silently deploy against the previous run's database.
SUCCESS=false
trap '[ "$SUCCESS" = true ] || echo "setup-db.sh did not finish: $ENV_FILE was NOT updated and still points to database ${PREV_DB_NAME:-<none>}. Fix the error above and rerun before ./run-pod.sh." >&2' EXIT

REUSE=false
if [ -n "$PREV_INSTANCE" ] && [ -n "$PREV_NAMESPACE" ]; then
    read -rp "Reuse the previous run's instance='$PREV_INSTANCE' and namespace='$PREV_NAMESPACE'? [Y/n] " ans
    case "${ans:-Y}" in [Nn]*) ;; *) REUSE=true ;; esac
fi

# Precedence: an explicit env var wins, then the reused previous value, then the built-in default.
if [ "$REUSE" = true ]; then
    INSTANCE="$PREV_INSTANCE"
    NAMESPACE="$PREV_NAMESPACE"
    PROJECT="${PROJECT:-${PREV_PROJECT:-$PROJECT_DEFAULT}}"
    DB_USER="${DB_USER:-${PREV_DB_USER:-$DB_USER_DEFAULT}}"
    echo "Reusing instance='$INSTANCE', namespace='$NAMESPACE' (project='$PROJECT')."
else
    PROJECT="${PROJECT:-$PROJECT_DEFAULT}"
    DB_USER="${DB_USER:-$DB_USER_DEFAULT}"
    read -rp "Cloud SQL instance name: " INSTANCE
    read -rp "Kubernetes namespace for the pod: " NAMESPACE
fi

# The pod connects directly to the instance's private IP; fetch it from gcloud (override $DB_HOST).
if [ -z "${DB_HOST:-}" ]; then
    # describe has no --filter (that's a list-command flag), so flatten the IPs and pick PRIVATE here.
    DB_HOST="$(gcloud sql instances describe "$INSTANCE" --project="$PROJECT" \
        --flatten='ipAddresses[]' \
        --format='csv[no-heading](ipAddresses.type,ipAddresses.ipAddress)' \
        | awk -F, '$1 == "PRIVATE" { print $2 }')"
    [ -n "$DB_HOST" ] || { echo "error: instance '$INSTANCE' has no private IP" >&2; exit 1; }
fi

# Unique DB per run; name is a safe unquoted Postgres identifier.
DB_NAME="nsim_$(openssl rand -hex 4)"

# 32-char password with one lower, upper, digit and non-alphanumeric (Cloud SQL policy), all
# URL-unreserved so DATABASE_URL needs no escaping. Each pipeline ends in `cut` (reads all input)
# so nothing is SIGPIPE-killed under pipefail.
PASSWORD="$(openssl rand -base64 32 | tr -dc 'a-z' | cut -c1-1)$(openssl rand -base64 32 | tr -dc 'A-Z' | cut -c1-1)$(openssl rand -base64 32 | tr -dc '0-9' | cut -c1-1)-$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-28)"

# Create the user, or reset its password if it already exists (so env.sh stays in sync).
echo "Creating database user '$DB_USER' on instance '$INSTANCE' ..."
if ! gcloud sql users create "$DB_USER" \
        --instance="$INSTANCE" --project="$PROJECT" --password="$PASSWORD" 2>/dev/null; then
    echo "  user already exists — resetting its password."
    gcloud sql users set-password "$DB_USER" \
        --instance="$INSTANCE" --project="$PROJECT" --password="$PASSWORD"
fi

echo "Creating database '$DB_NAME' on instance '$INSTANCE' ..."
gcloud sql databases create "$DB_NAME" --instance="$INSTANCE" --project="$PROJECT"

DATABASE_URL="postgresql://${DB_USER}:${PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"

# 0600 — env.sh holds the DB password.
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by setup-db.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ') — DO NOT COMMIT.
# Sourced by run-pod.sh.
export PROJECT="$PROJECT"
export INSTANCE="$INSTANCE"
export NAMESPACE="$NAMESPACE"
export DB_USER="$DB_USER"
export DB_NAME="$DB_NAME"
export DATABASE_URL="$DATABASE_URL"
EOF
SUCCESS=true

echo "Wrote $ENV_FILE (gitignored): namespace=$NAMESPACE, database=$DB_NAME."
echo "Next: ./run-pod.sh"
