//! OpenAPI description of the HTTP API, derived from the `#[utoipa::path]` annotations on the
//! handlers, plus the markdown renderer behind `docs/metadata-service-api.md` (regenerated by
//! `tests/api_doc.rs`; run with `UPDATE_API_DOC=1` to bless changes).

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "metadata-service",
        description = "Ingesters report chunk metadata here instead of the scheduler discovering \
                       it from S3. A 2xx insert is durably accepted — overlap is decided at insert \
                       time, under a per-dataset lock (ADR 0003)."
    ),
    paths(
        crate::handlers::create_dataset,
        crate::handlers::post_write_schema,
        crate::handlers::get_write_schemas,
        crate::handlers::get_write_schema,
        crate::handlers::put_read_schema,
        crate::handlers::get_read_schema,
        crate::handlers::post_chunks,
        crate::handlers::post_corrections,
        crate::handlers::get_head,
        crate::handlers::get_chunk_status,
        crate::handlers::health,
        crate::handlers::metrics,
    ),
    modifiers(&BearerAuth),
    tags(
        (name = "admin", description = "Admin token required"),
        (name = "schemas", description = "Dataset-scoped token"),
        (name = "chunks", description = "Dataset-scoped token"),
        (name = "ops", description = "Unauthenticated")
    )
)]
pub struct ApiDoc;

struct BearerAuth;
impl Modify for BearerAuth {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        openapi
            .components
            .get_or_insert_default()
            .add_security_scheme(
                "bearer",
                SecurityScheme::Http(HttpBuilder::new().scheme(HttpAuthScheme::Bearer).build()),
            );
    }
}

/// Render the spec as the markdown committed at `docs/metadata-service-api.md`. Hand-rolled so the doc pipeline
/// stays in-repo; covers what this API uses (JSON bodies, path params, component schemas).
pub fn render_markdown(spec: &utoipa::openapi::OpenApi) -> String {
    let v = serde_json::to_value(spec).expect("spec serializes");
    let mut out = String::new();
    let info = &v["info"];
    out.push_str(&format!(
        "# {} — HTTP API\n\n{}\n\n",
        info["title"].as_str().unwrap_or("API"),
        info["description"].as_str().unwrap_or("")
    ));
    out.push_str(
        "Generated from the `#[utoipa::path]` annotations — do not edit by hand. \
         Regenerate: `UPDATE_API_DOC=1 cargo test -p metadata-service --test api_doc`.\n\n\
         Authentication: `Authorization: Bearer <token>`. Admin endpoints need an admin token; \
         dataset endpoints need a token scoped to that dataset; `/health` and `/metrics` are open.\n",
    );

    if let Some(paths) = v["paths"].as_object() {
        for (path, methods) in paths {
            let Some(methods) = methods.as_object() else {
                continue;
            };
            for (method, op) in methods {
                out.push_str(&format!("\n## `{} {}`\n\n", method.to_uppercase(), path));
                // utoipa: doc comment's first line → summary, remainder → description.
                let blurb = [&op["summary"], &op["description"]]
                    .iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| s.replace('\n', " "))
                    .collect::<Vec<_>>()
                    .join(" ");
                if !blurb.is_empty() {
                    out.push_str(&format!("{blurb}\n\n"));
                }
                if let Some(params) = op["parameters"].as_array().filter(|p| !p.is_empty()) {
                    out.push_str("Path parameters:\n");
                    for p in params {
                        out.push_str(&format!(
                            "- `{}` ({}) — {}\n",
                            p["name"].as_str().unwrap_or("?"),
                            schema_type(&p["schema"]),
                            p["description"].as_str().unwrap_or(""),
                        ));
                    }
                    out.push('\n');
                }
                if let Some(body) =
                    op["requestBody"]["content"]["application/json"]["schema"].as_object()
                {
                    out.push_str(&format!(
                        "Request body: {}\n\n",
                        schema_ref(&serde_json::Value::Object(body.clone()))
                    ));
                }
                if let Some(responses) = op["responses"].as_object() {
                    out.push_str("Responses:\n");
                    for (status, r) in responses {
                        let body = r["content"]["application/json"]["schema"]
                            .as_object()
                            .map(|s| {
                                format!(" — {}", schema_ref(&serde_json::Value::Object(s.clone())))
                            })
                            .unwrap_or_default();
                        out.push_str(&format!(
                            "- `{}` {}{}\n",
                            status,
                            r["description"].as_str().unwrap_or(""),
                            body
                        ));
                    }
                }
            }
        }
    }

    if let Some(schemas) = v["components"]["schemas"].as_object() {
        out.push_str("\n# Schemas\n");
        for (name, schema) in schemas {
            out.push_str(&format!("\n## `{name}`\n\n"));
            render_schema(&mut out, schema);
        }
    }
    out
}

fn render_schema(out: &mut String, schema: &serde_json::Value) {
    if let Some(vals) = schema["enum"].as_array() {
        let vals: Vec<String> = vals.iter().map(|x| format!("`{x}`")).collect();
        out.push_str(&format!("One of: {}\n", vals.join(", ")));
        return;
    }
    let empty = serde_json::Map::new();
    let props = schema["properties"].as_object().unwrap_or(&empty);
    if props.is_empty() {
        out.push_str(&format!("Type: {}\n", schema_type(schema)));
        return;
    }
    let required: Vec<&str> = schema["required"]
        .as_array()
        .map(|a| a.iter().filter_map(|x| x.as_str()).collect())
        .unwrap_or_default();
    out.push_str("| field | type | required | notes |\n|---|---|---|---|\n");
    for (field, fs) in props {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            field,
            schema_type(fs),
            if required.contains(&field.as_str()) {
                "yes"
            } else {
                ""
            },
            fs["description"].as_str().unwrap_or("").replace('\n', " "),
        ));
    }
}

/// Human name for a schema node: a `$ref` renders as a link to its section, everything else as a
/// plain type word (arrays recurse).
fn schema_ref(s: &serde_json::Value) -> String {
    if let Some(r) = s["$ref"].as_str() {
        let name = r.rsplit('/').next().unwrap_or(r);
        return format!("[`{name}`](#{})", name.to_lowercase());
    }
    if s["type"].as_str() == Some("array") {
        return format!("array of {}", schema_ref(&s["items"]));
    }
    schema_type(s)
}

fn schema_type(s: &serde_json::Value) -> String {
    if s["$ref"].is_string() {
        return schema_ref(s);
    }
    match s["type"].as_str() {
        Some("array") => format!("array of {}", schema_type(&s["items"])),
        Some(t) => {
            // Nullable renders as `type?`; additionalProperties as a map.
            let mut t = t.to_string();
            if s["additionalProperties"].is_object() {
                t = format!("map of {}", schema_type(&s["additionalProperties"]));
            }
            t
        }
        None => "object".to_string(),
    }
}
